# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ea92c69954f0969c4b1d644ca51f42df897cf08d8331eb800924248344287a2a7da4692c3f03b74dac2569893cf0b1d61e713c2c9109673fc4003c02153a876d

test:
  secret_key_base: bbd998d44595bbcc2d580761bd2bd4ac024a29465f95c499f443e6b5b09daf1e4eea946db31890d9d9ad66a86d4df26608b634f259dfb5aa16a7d56570ba7718

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
